### ISSUE TITLE
Recent Ubuntu update conflicts with HTTP GET /config

### ISSUE THREAD

**Issue by mwfarb** [netsec-ethz/scion-viz#52]
Appears we may need to pin specific crypto version in requirements.txt at least. Needs more investigation. Django stack trace attached.
[scion-viz py3 ssl error.log](https://github.com/netsec-ethz/scion-viz/files/2601346/scion-viz.py3.ssl.error.log)

**Comment by matzf** [comment]
Repository archived, closed.
